# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/SDx/2016.4/Vivado/bin/project_new/project_new.cache/wt [current_project]
set_property parent.project_path /home/SDx/2016.4/Vivado/bin/project_new/project_new.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_output_repo /home/SDx/2016.4/Vivado/bin/project_new/project_new.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files {{/root/Downloads/control logic/file.coe}}
read_verilog -library xil_defaultlib {
  /root/Downloads/encoder_256_8.v
  {/root/Downloads/control logic/priority4bit.v}
  {/root/Downloads/control logic/ce.v}
  {/root/Downloads/control logic/adder.v}
  {/root/Downloads/control logic/priority256bit.v}
  {/root/Downloads/control logic/cu.v}
  {/root/Downloads/control logic/rca5.v}
  {/root/Downloads/control logic/ex1.v}
}
read_ip -quiet /home/SDx/2016.4/Vivado/bin/project_new/project_new.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all /home/SDx/2016.4/Vivado/bin/project_new/project_new.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]
set_property is_locked true [get_files /home/SDx/2016.4/Vivado/bin/project_new/project_new.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/SDx/2016.4/Vivado/bin/project_new/project_new.srcs/constrs_1/new/cons1.xdc
set_property used_in_implementation false [get_files /home/SDx/2016.4/Vivado/bin/project_new/project_new.srcs/constrs_1/new/cons1.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top pe_cu -part xc7z020clg484-1


write_checkpoint -force -noxdef pe_cu.dcp

catch { report_utilization -file pe_cu_utilization_synth.rpt -pb pe_cu_utilization_synth.pb }
